--<ScriptOptions statementTerminator=";"/>

CREATE SCHEMA "FGC_TRAINING_DEV" AUTHORIZATION "FGC_TRAINING_DEV";


--########################################################################################
--# START: Core system tables (EXCL. Reference Data tables)
--########################################################################################
CREATE TABLE "FGC_TRAINING_DEV"."CHANGE_CONTROL" (
		"CHANGE_ID" CHAR(36) NOT NULL,
    CONSTRAINT "PK" PRIMARY KEY("CHANGE_ID"),
		"CHANGE_CREATED_TMS"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT TIMESTAMP, 
		"CHANGE_CREATED_BY"    VARCHAR(12 OCTETS) NOT NULL, 
		"CHANGE_CURRENT_OWNER" VARCHAR(12 OCTETS) NOT NULL, --this shifts around as ownership of the change session is transferred.
		"CHANGE_MODIFIED_TMS"  TIMESTAMP(3) DEFAULT NULL, --used when editor clicks "save" but does not commit their changes to the published version (stays as an active change session)
		"CHANGE_COMMITTED_TMS" TIMESTAMP(3) DEFAULT NULL,
		"CHANGE_COMMITTED_BY"  VARCHAR(12 OCTETS) DEFAULT NULL --this tells us who chose to overwrite the published version and store the old data in the history.
)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;
	
CREATE TABLE "FGC_TRAINING_DEV"."TRAINING_CATALOGUES" (
		"C_ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 0 INCREMENT BY 1 MINVALUE 0 NO CYCLE NO CACHE NO ORDER ), 
		CONSTRAINT "PK" PRIMARY KEY("C_ID"),
		"C_NAME" VARCHAR(100 OCTETS) NOT NULL, 
		"C_DESC" VARCHAR(250 OCTETS) DEFAULT NULL, 
		"ADDED_TMS" TIMESTAMP(3) NOT NULL DEFAULT CURRENT TIMESTAMP, 
		"ADDED_BY" VARCHAR(12 OCTETS) NOT NULL DEFAULT 'SYSTEM', 
		"ARCHIVED_TMS" TIMESTAMP(3) DEFAULT NULL, 
		"ARCHIVED_BY" VARCHAR(12 OCTETS) DEFAULT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;

--########################################################################################
--# START: UNUSED TABLES NEED TO BE CHANGED / DELETED / ???
--########################################################################################
CREATE TABLE "FGC_TRAINING_DEV"."ATTENDANCE_CANCELLATION_APPROVALS" (
		"ACS_ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 0 INCREMENT BY 1 MINVALUE 0 NO CYCLE NO CACHE NO ORDER ), 
		"ACR_ID" BIGINT NOT NULL, 
		CONSTRAINT "PK" PRIMARY KEY("ACS_ID"),
		"SIFNOFF_STAGE" VARCHAR(12 OCTETS) NOT NULL, 
		"SIGNOFF_ON" TIMESTAMP(3), 
		"SIGNOFF_BY" VARCHAR(12 OCTETS), 
		"SIGNOFF_NOTES" VARCHAR(5000 OCTETS), 
		"SIGNOFF_DECISION" VARCHAR(20 OCTETS)
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "FGC_TRAINING_DEV"."ATTENDANCE_CANCELLATION_REQUESTS" (
		"ACR_ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 0 INCREMENT BY 1 MINVALUE 0 NO CYCLE NO CACHE NO ORDER ), 
		"AR_ID" BIGINT NOT NULL, 
		CONSTRAINT "PK" PRIMARY KEY("ACR_ID"),
		"REQUEST_TYPE" VARCHAR(50 OCTETS) NOT NULL, 
		"REQUESTED_ON" TIMESTAMP(3) NOT NULL, 
		"REQUESTED_BY" VARCHAR(12 OCTETS) NOT NULL, 
		"ADDITIONAL_NOTES" VARCHAR(5000 OCTETS), 
		"REQUEST_STATUS" VARCHAR(20 OCTETS) NOT NULL, 
		"COURSE_INSTANCE_ID" BIGINT DEFAULT NULL, 
		"EVENT_INSTANCE_ID" BIGINT DEFAULT NULL, 
		"ATTENDEE_ID" VARCHAR(12 OCTETS) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;


--########################################################################################
--# START: CHANGE SESSION (current working copies) for Course Instances, Event Instances, Relational Data and Bookings (NOT attendance)
--########################################################################################
CREATE TABLE "FGC_TRAINING_DEV"."CHANGE_COURSE_INSTANCES" (
		"CHANGE_ID" CHAR(36) NOT NULL,
    CONSTRAINT "PK" PRIMARY KEY("CHANGE_ID"),
		"COURSE_INSTANCE_ID" BIGINT NOT NULL, 
		CONSTRAINT "CON_UNIQUEROWS" UNIQUE("CHANGE_ID", "COURSE_INSTANCE_ID"),
		"COURSE_TEMPLATE_ID" BIGINT DEFAULT NULL, 		
		"CATALOGUE_ID" INTEGER NOT NULL, 
		"VENDOR_ID" BIGINT NOT NULL, 
		"COURSE_NAME" VARCHAR(200 OCTETS) NOT NULL, 
		"COURSE_DESC" VARCHAR(1000 OCTETS) NOT NULL DEFAULT '', 
		"COURSE_START_DATETIME" TIMESTAMP(3) NOT NULL, 
		"COURSE_END_DATETIME" TIMESTAMP(3) NOT NULL, 
		"COURSE_LEN_TU" INTEGER DEFAULT NULL, 
		"COURSE_LEN_TV" SMALLINT DEFAULT NULL, 
		"NUM_EVENTS" SMALLINT NOT NULL DEFAULT 0,
		"COURSE_NOTES" VARCHAR(1000 OCTETS) NOT NULL DEFAULT '', 
		"RT_REQUIRED" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_RTREQUIRED" CHECK ( RT_REQUIRED in(0,1) ),
		"RT_REQ_EVERY_TU" INTEGER DEFAULT NULL, 
		"RT_REQ_EVERY_TV" SMALLINT DEFAULT NULL, 
		"PHASE_NUM" SMALLINT DEFAULT NULL, 
		CONSTRAINT "CON_PHASENUM" CHECK ( PHASE_NUM in( null, 1, 2, 3 ) ),
		"ILEARN_FLAG" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_ILEARNFLAG" CHECK ( ILEARN_FLAG in(0,1) ),
		"MIN_NUM_ATTENDEES" SMALLINT DEFAULT NULL, 
		"MAX_NUM_ATTENDEES" SMALLINT DEFAULT NULL, 
		"ATTENDEE_REQS" VARCHAR(1000 OCTETS) NOT NULL DEFAULT '', 
		"IS_MANDATORY" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_ISMANDATORY" CHECK ( IS_MANDATORY in(0,1) ),
		"EQUIPCLOTHING_REQS" VARCHAR(500 OCTETS) NOT NULL DEFAULT '', 
		"LUNCH_PROVIDED" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_LUNCHPROVIDED" CHECK ( LUNCH_PROVIDED in(0,1) ),
		"TRAINER_REQS" VARCHAR(1000 OCTETS) NOT NULL DEFAULT '', 
		"SELF_BOOKABLE" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_SELFBOOKABLE" CHECK ( SELF_BOOKABLE in(0,1) ),
		"SELF_BOOK_TV" SMALLINT DEFAULT NULL, 
		"SELF_BOOK_TU" INTEGER DEFAULT NULL, 
		"SELF_CANCELLABLE" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_SELFCANCELLABLE" CHECK ( SELF_CANCELLABLE in(0,1) ),
		"SELF_CANC_TV" SMALLINT DEFAULT NULL, 
		"SELF_CANC_TU" INTEGER DEFAULT NULL,
		"CANCELLED_TMS"     TIMESTAMP(3) DEFAULT NULL, 
		"CANCELLED_BY"      VARCHAR(12 OCTETS) DEFAULT NULL, 
		"CANCELLED_REASONS" VARCHAR(500 OCTETS) NOT NULL DEFAULT ''
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;
CREATE TABLE "FGC_TRAINING_DEV"."CHANGE_COURSE_INST_BOOK_APPROVAL_PARTIES" (
		"CHANGE_ID"   CHAR(36) NOT NULL,
		"INSTANCE_ID" BIGINT NOT NULL, 
		"PARTY_ID"    BIGINT NOT NULL,
    CONSTRAINT "CON_UNIQUEROWS" UNIQUE("CHANGE_ID", "INSTANCE_ID", "PARTY_ID")
)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;
CREATE TABLE "FGC_TRAINING_DEV"."CHANGE_COURSE_INST_CANC_APPROVAL_PARTIES" (
		"CHANGE_ID"   CHAR(36) NOT NULL,
		"INSTANCE_ID" BIGINT NOT NULL, 
		"PARTY_ID"    BIGINT NOT NULL,
    CONSTRAINT "CON_UNIQUEROWS" UNIQUE("CHANGE_ID", "INSTANCE_ID", "PARTY_ID")
)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;
CREATE TABLE "FGC_TRAINING_DEV"."CHANGE_EVENT_INSTANCES" (
    "CHANGE_ID" CHAR(36) NOT NULL,
		"EVENT_INSTANCE_ID" BIGINT NOT NULL, 
		CONSTRAINT "CON_UNIQUEROWS" UNIQUE("CHANGE_ID", "EVENT_INSTANCE_ID"), --this is really our PK.
		"IS_NEW" DECIMAL(1,0) NOT NULL DEFAULT 0,
		CONSTRAINT "CON_ISNEW" CHECK( IS_NEW in(0,1) ),
		"EVENT_TEMPLATE_ID"  BIGINT DEFAULT NULL, 		
		"COURSE_INSTANCE_ID" BIGINT DEFAULT NULL, 
		"CATALOGUE_ID" INTEGER NOT NULL, 
		"VENDOR_ID"    BIGINT DEFAULT NULL, 
		"EVENT_NAME_PREFIX" VARCHAR(40 OCTETS) DEFAULT NULL, 
		"EVENT_NAME" VARCHAR(200 OCTETS) NOT NULL, 
		"EVENT_DESC" VARCHAR(1000 OCTETS) NOT NULL DEFAULT '', 
		"START_DATETIME" TIMESTAMP(3) NOT NULL, 
		"END_DATETIME"   TIMESTAMP(3) NOT NULL, 
		"TIME_UNIT_ID" INTEGER DEFAULT NULL, 
		"TIME_VALUE"   SMALLINT DEFAULT NULL, 
		"LOCATION_ID" BIGINT DEFAULT NULL, 
		"INTRA_LOCATION_DETAIL" VARCHAR(1000 OCTETS) NOT NULL DEFAULT '', 
		"PHASE_NUM" SMALLINT DEFAULT NULL, 
		CONSTRAINT "CON_PHASENUM" CHECK ( PHASE_NUM in( null, 1, 2, 3 ) ),
		"ILEARN_FLAG" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_ILEARNFLAG" CHECK ( ILEARN_FLAG in(0,1) ),
		"MIN_NUM_ATTENDEES" SMALLINT DEFAULT NULL, 
		"MAX_NUM_ATTENDEES" SMALLINT DEFAULT NULL, 
		"ATTENDEE_REQS" VARCHAR(1000 OCTETS) NOT NULL DEFAULT '', 
		"IS_MANDATORY"  DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
    CONSTRAINT "CON_ISMANDATORY" CHECK ( IS_MANDATORY in(0,1) ),
		"EQUIPCLOTHING_REQS"  VARCHAR(500 OCTETS) NOT NULL DEFAULT '', 
		"OBJECTIVES_OUTCOMES" VARCHAR(1000 OCTETS) NOT NULL DEFAULT '', 
		"LUNCH_PROVIDED" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_LUNCHPROVIDED" CHECK ( LUNCH_PROVIDED in(0,1) ),
		"SELF_BOOKABLE" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_SELFBOOKABLE" CHECK ( SELF_BOOKABLE in(0,1) ),
		"SELF_BOOK_TV" SMALLINT DEFAULT NULL, 
		"SELF_BOOK_TU" INTEGER DEFAULT NULL, 
		"SELF_CANCELLABLE" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_SELFCANCELLABLE" CHECK ( SELF_CANCELLABLE in(0,1) ),
		"SELF_CANC_TV" SMALLINT DEFAULT NULL, 
		"SELF_CANC_TU" INTEGER DEFAULT NULL,
		"TRAINER_REQS" VARCHAR(1000 OCTETS) NOT NULL DEFAULT '', 
		"CANCELLED_TMS"     TIMESTAMP(3) DEFAULT NULL, 
		"CANCELLED_BY"      VARCHAR(12 OCTETS) DEFAULT NULL, 
		"CANCELLED_REASONS" VARCHAR(500 OCTETS) NOT NULL DEFAULT '', 
		"MODIFIED_TMS" TIMESTAMP(3) NULL DEFAULT NULL,
		"MODIFIED_BY" VARCHAR(12) NULL DEFAULT NULL,
		"MODIFIED_REASONS" VARCHAR(500) NOT NULL DEFAULT '',
		"ATTENDANCE_PUBLISHED_TMS" TIMESTAMP(3) DEFAULT NULL, 
		"ATTENDANCE_PUBLISHED_BY"  VARCHAR(12 OCTETS) DEFAULT NULL
		)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;
CREATE TABLE "FGC_TRAINING_DEV"."CHANGE_EVENT_INST_BOOKINGS" (
		"CHANGE_ID" CHAR(36 OCTETS) NOT NULL, 
		"DELEGATE_ID" VARCHAR(12 OCTETS) NOT NULL, 
		"EVENT_ID" BIGINT NOT NULL, 
		CONSTRAINT "CON_UNIQUEROWS" UNIQUE("CHANGE_ID", "DELEGATE_ID", "EVENT_ID"), --this is really our PK.
		"BOOKING_STATUS_ID" SMALLINT NOT NULL,
		"BOOKING_UPDATED_ON" timestamp(3) NULL default NULL,
		"BOOKING_UPDATED_BY" varchar(12)  NULL default NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;	


--########################################################################################
--# START: INSTANCE DATA (current published copy) for Course Instances, Event Instances, Relational Data and Bookings AND attendance
--########################################################################################
CREATE TABLE "FGC_TRAINING_DEV"."COURSE_EVENT_NOTES" (
		"CEN_ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 0 INCREMENT BY 1 MINVALUE 0 NO CYCLE NO CACHE NO ORDER ), 
		CONSTRAINT "PK" PRIMARY KEY("CEN_ID"),
		"COURSE_INSTANCE_ID" BIGINT, 
		"EVENT_INSTANCE_ID" BIGINT, 
		"NOTES_ADDED_BY" VARCHAR(12 OCTETS), 
		"NOTES_ADDED_ON" TIMESTAMP(3), 
		"NOTES" VARCHAR(1000 OCTETS)
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;
CREATE TABLE "FGC_TRAINING_DEV"."COURSE_INSTANCES" (
		"I_ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 0 INCREMENT BY 1 MINVALUE 0 NO CYCLE NO CACHE NO ORDER ), 
		CONSTRAINT "PK" PRIMARY KEY("I_ID"),
		"CATALOGUE_ID" INTEGER NOT NULL, 
		"COURSE_TEMPLATE_ID" BIGINT DEFAULT NULL, 
		"VENDOR_ID" BIGINT NOT NULL, 
		"COURSE_NAME" VARCHAR(200 OCTETS) NOT NULL, 
		"COURSE_DESC" VARCHAR(1000 OCTETS) NOT NULL DEFAULT '', 
		"PHASE_NUM" SMALLINT DEFAULT NULL, 
		CONSTRAINT "CON_PHASENUM" CHECK ( PHASE_NUM in( null, 1, 2, 3 ) ),
		"ILEARN_FLAG" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_ILEARNFLAG" CHECK ( ILEARN_FLAG in(0,1) ),
		"MIN_NUM_ATTENDEES" SMALLINT DEFAULT NULL, 
		"MAX_NUM_ATTENDEES" SMALLINT DEFAULT NULL, 
		"ATTENDEE_REQS" VARCHAR(1000 OCTETS) NOT NULL DEFAULT '', 
		"TRAINER_REQS" VARCHAR(1000 OCTETS) NOT NULL DEFAULT '', 
		"COURSE_START_DATETIME" TIMESTAMP(3) NOT NULL, 
		"COURSE_LEN_TU" INTEGER DEFAULT NULL, 
		"COURSE_LEN_TV" SMALLINT DEFAULT NULL, 
		"NUM_EVENTS" SMALLINT NOT NULL DEFAULT 0, 
		"RT_REQUIRED" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_RTREQUIRED" CHECK ( RT_REQUIRED in(0,1) ),
		"RT_REQ_EVERY_TU" INTEGER DEFAULT NULL, 
		"RT_REQ_EVERY_TV" SMALLINT DEFAULT NULL, 
		"CREATED_TMS" TIMESTAMP(3) NOT NULL DEFAULT CURRENT TIMESTAMP, 
		"CREATED_BY" VARCHAR(12 OCTETS) NOT NULL, 
		"MODIFIED_TMS" TIMESTAMP(3) DEFAULT NULL, 
		"MODIFIED_BY" VARCHAR(12 OCTETS) DEFAULT NULL, 
		"MODIFIED_REASONS" VARCHAR(500 OCTETS) NOT NULL DEFAULT '', 
		"CANCELLED_TMS" TIMESTAMP(3) DEFAULT NULL, 
		"CANCELLED_BY" VARCHAR(12 OCTETS) DEFAULT NULL, 
		"CANCELLED_REASONS" VARCHAR(500 OCTETS) NOT NULL DEFAULT '', 
		"COURSE_END_DATETIME" TIMESTAMP(3) NOT NULL, 
		"EQUIPCLOTHING_REQS" VARCHAR(500 OCTETS) NOT NULL DEFAULT '', 
		"LUNCH_PROVIDED" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_LUNCHPROVIDED" CHECK ( LUNCH_PROVIDED in(0,1) ),
		"COURSE_NOTES" VARCHAR(1000 OCTETS) NOT NULL DEFAULT '', 
		"IS_MANDATORY" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_ISMANDATORY" CHECK ( IS_MANDATORY in(0,1) ),
		"SELF_BOOKABLE" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_SELFBOOKABLE" CHECK ( SELF_BOOKABLE in(0,1) ),
		"SELF_BOOK_TV" SMALLINT DEFAULT NULL, 
		"SELF_BOOK_TU" INTEGER DEFAULT NULL, 
		"SELF_CANCELLABLE" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_SELFCANCELLABLE" CHECK ( SELF_CANCELLABLE in(0,1) ),
		"SELF_CANC_TV" SMALLINT DEFAULT NULL, 
		"SELF_CANC_TU" INTEGER DEFAULT NULL 
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;
CREATE TABLE "FGC_TRAINING_DEV"."COURSE_INST_ADMINISTRATORS" (
		"INSTANCE_ID" BIGINT NOT NULL, 
		"ADMINISTRATOR_ID" BIGINT NOT NULL, 
		"SEQ_NUM" SMALLINT NOT NULL DEFAULT 0
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;
CREATE TABLE "FGC_TRAINING_DEV"."COURSE_INST_BOOK_APPROVAL_PARTIES" (
		"INSTANCE_ID" BIGINT NOT NULL, 
		"PARTY_ID" BIGINT NOT NULL,
		CONSTRAINT "CON_UNIQUEROWS" UNIQUE("INSTANCE_ID", "PARTY_ID")
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;
CREATE TABLE "FGC_TRAINING_DEV"."COURSE_INST_CANC_APPROVAL_PARTIES" (
		"INSTANCE_ID" BIGINT NOT NULL, 
		"PARTY_ID" BIGINT NOT NULL,
		CONSTRAINT "CON_UNIQUEROWS" UNIQUE("INSTANCE_ID", "PARTY_ID")
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;
CREATE TABLE "FGC_TRAINING_DEV"."COURSE_INST_TRAINERS" (
		"INSTANCE_ID" BIGINT NOT NULL, 
		"TRAINER_ID" BIGINT NOT NULL, 
		"SEQ_NUM" SMALLINT NOT NULL DEFAULT 0,
		CONSTRAINT "CON_UNIQUEROWS" UNIQUE("INSTANCE_ID", "TRAINER_ID")
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;
CREATE TABLE "FGC_TRAINING_DEV"."EVENT_INSTANCES" (
		"I_ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 0 INCREMENT BY 1 MINVALUE 0 NO CYCLE NO CACHE NO ORDER ), 
		CONSTRAINT "PK" PRIMARY KEY("I_ID"),
		"I_ID__PRE" BIGINT NULL DEFAULT NULL, --any NEW event added under a change session will be authored in table CHANGE_EVENT_INSTANCES and will therefore have a different ID value until committed to THIS table. We have to store that "initial ID" here when publishing those changes in order to insert any bookings (correlating to this value) with the real I_ID generated upon insert.
		"COURSE_INSTANCE_ID" BIGINT DEFAULT NULL, 
		"EVENT_TEMPLATE_ID" BIGINT DEFAULT NULL, 
		"CATALOGUE_ID" INTEGER NOT NULL, 
		"VENDOR_ID" BIGINT DEFAULT NULL, 
		"EVENT_NAME_PREFIX" VARCHAR(40 OCTETS) DEFAULT NULL, 
		"EVENT_NAME_SHORT" VARCHAR(24 OCTETS) NOT NULL DEFAULT '', 
		"EVENT_NAME" VARCHAR(200 OCTETS) NOT NULL, 
		"EVENT_DESC" VARCHAR(1000 OCTETS) NOT NULL DEFAULT '', 
		"PHASE_NUM" SMALLINT DEFAULT NULL, 
		CONSTRAINT "CON_PHASENUM" CHECK ( PHASE_NUM       in( null, 1, 2, 3 ) ),
		"ILEARN_FLAG" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_ILEARNFLAG" CHECK ( ILEARN_FLAG     in(0,1) ),
		"MIN_NUM_ATTENDEES" SMALLINT DEFAULT NULL, 
		"MAX_NUM_ATTENDEES" SMALLINT DEFAULT NULL, 
		"START_DATETIME" TIMESTAMP(3) NOT NULL, 
		"END_DATETIME" TIMESTAMP(3) NOT NULL, 
		"TIME_UNIT_ID" INTEGER DEFAULT NULL, 
		"TIME_VALUE" SMALLINT DEFAULT NULL, 
		"LOCATION_ID" BIGINT DEFAULT NULL, 
		"INTRA_LOCATION_DETAIL" VARCHAR(1000 OCTETS) NOT NULL DEFAULT '', 
		"ATTENDEE_REQS" VARCHAR(1000 OCTETS) NOT NULL DEFAULT '', 
		"TRAINER_REQS" VARCHAR(1000 OCTETS) NOT NULL DEFAULT '', 
		"CREATED_TMS" TIMESTAMP(3) NOT NULL DEFAULT CURRENT TIMESTAMP, 
		"CREATED_BY" VARCHAR(12 OCTETS) NOT NULL, 
		"MODIFIED_TMS" TIMESTAMP(3) DEFAULT NULL, 
		"MODIFIED_BY" VARCHAR(12 OCTETS) DEFAULT NULL, 
		"MODIFIED_REASONS" VARCHAR(500 OCTETS) NOT NULL DEFAULT '', 
		"CANCELLED_TMS" TIMESTAMP(3) DEFAULT NULL, 
		"CANCELLED_BY" VARCHAR(12 OCTETS) DEFAULT NULL, 
		"CANCELLED_REASONS" VARCHAR(500 OCTETS) NOT NULL DEFAULT '', 
		"EQUIPCLOTHING_REQS" VARCHAR(500 OCTETS) NOT NULL DEFAULT '', 
		"LUNCH_PROVIDED" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_LUNCHPROVIDED" CHECK ( LUNCH_PROVIDED in(0,1) ),
		"OBJECTIVES_OUTCOMES" VARCHAR(1000 OCTETS) NOT NULL DEFAULT '', 
		"ATTENDANCE_PUBLISHED_TMS" TIMESTAMP(3) DEFAULT NULL, 
		"ATTENDANCE_PUBLISHED_BY" VARCHAR(12 OCTETS) DEFAULT NULL, 
		"IS_MANDATORY" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_ISMANDATORY" CHECK ( IS_MANDATORY     in(0,1) ),
		"SELF_BOOKABLE" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_SELFBOOKABLE" CHECK ( SELF_BOOKABLE   in(0,1) ),
		"SELF_BOOK_TV" SMALLINT DEFAULT NULL, 
		"SELF_BOOK_TU" INTEGER DEFAULT NULL, 
		"SELF_CANCELLABLE" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_SELFCANCELLABLE" CHECK ( SELF_CANCELLABLE in(0,1) ),
		"SELF_CANC_TV" SMALLINT DEFAULT NULL, 
		"SELF_CANC_TU" INTEGER DEFAULT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;
CREATE TABLE "FGC_TRAINING_DEV"."EVENT_INST_BOOKINGS_HISTORY" (
  "DELEGATE_ID"       VARCHAR(12 OCTETS) NOT NULL,
  "EVENT_INSTANCE_ID" BIGINT NOT NULL,
  "ADDED_TMS"         TIMESTAMP(3) NOT NULL, -- No default:  This is fed to us from application code because the exact same value is put into multiple tables. This 
	                                           --              column's name actually means "when was this ROW added" and as well as changes we also store the original row.
																						 -- See related: this.CHANGE_ID which is a UUID.
  CONSTRAINT "PK" PRIMARY KEY 
	  ("DELEGATE_ID", 
	   "EVENT_INSTANCE_ID", 
	   "ADDED_TMS"
	  ),
  "ADDED_BY"          VARCHAR(12 OCTETS) NOT NULL,
  "BOOKING_STATUS_ID" SMALLINT NOT NULL,
  "CHANGE_ID"         CHAR(36 OCTETS) NOT NULL --All bookings and cancellations will be due to a generated Version ID (a UUID) that goes in here, INCLUDING initial bookings.
);
CREATE TABLE "FGC_TRAINING_DEV"."EVENT_INST_ATTENDANCE" (
		"EVENT_INSTANCE_ID" BIGINT NOT NULL, 
		"ATTENDEE_ID" VARCHAR(12 OCTETS) NOT NULL, 
		CONSTRAINT "PK" PRIMARY KEY("ATTENDEE_ID", "EVENT_INSTANCE_ID"),
		"ATTENDEE_ADDED_ON" TIMESTAMP(3) NOT NULL DEFAULT CURRENT TIMESTAMP, 
		"ATTENDEE_ADDED_BY" VARCHAR(12 OCTETS), 
		"ATTENDANCE_UPDATE_ON" TIMESTAMP(3), 
		"ATTENDANCE_UPDATE_BY" VARCHAR(12 OCTETS), 
		"REASON_FOR_NONATTENDANCE" VARCHAR(5000 OCTETS), 
		"INJURY_OCCURRED" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		"INJURY_OCCURRED_DETAILS" VARCHAR(5000 OCTETS), 
		"ADDITIONAL_NOTES" VARCHAR(5000 OCTETS), 
		"ATT_STATUS_ID" SMALLINT DEFAULT NULL, 
		"BOOKING_STATUS_ID" SMALLINT NOT NULL DEFAULT 1, 
		"BOOKING_UPDATED_ON" TIMESTAMP(3) DEFAULT NULL, 
		"BOOKING_UPDATED_BY" VARCHAR(12 OCTETS) DEFAULT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;
	
--########################################################################################
--# START: TEMPLATE DATA for Course, Event, Relational Data
--########################################################################################
CREATE TABLE "FGC_TRAINING_DEV"."COURSE_TEMPLATES" (
		"T_ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 0 INCREMENT BY 1 MINVALUE 0 NO CYCLE NO CACHE NO ORDER ), 
		CONSTRAINT "PK" PRIMARY KEY("T_ID"),
		"CATALOGUE_ID" INTEGER NOT NULL, 
		"VENDOR_ID" BIGINT NOT NULL, 
		"COURSE_NAME" VARCHAR(200 OCTETS) NOT NULL, 
		"COURSE_DESC" VARCHAR(1000 OCTETS) NOT NULL DEFAULT '', 
		"PHASE_NUM" SMALLINT DEFAULT NULL, 
		CONSTRAINT "CON_PHASENUM" CHECK ( PHASE_NUM in( null, 1, 2, 3 ) ),
		"ILEARN_FLAG" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_ILEARNFLAG" CHECK ( ILEARN_FLAG in(0,1) ),
		"MIN_NUM_ATTENDEES" SMALLINT DEFAULT NULL, 
		"MAX_NUM_ATTENDEES" SMALLINT DEFAULT NULL, 
		"ATTENDEE_REQS" VARCHAR(1000 OCTETS) NOT NULL DEFAULT '', 
		"TRAINER_REQS" VARCHAR(1000 OCTETS) NOT NULL DEFAULT '', 
		"NUM_EVENTS" SMALLINT NOT NULL DEFAULT 0, 
		"COURSE_LEN_TU" INTEGER DEFAULT NULL, 
		"COURSE_LEN_TV" SMALLINT DEFAULT NULL, 
		"LEN_BET_EVENTS_TU" INTEGER DEFAULT NULL, 
		"LEN_BET_EVENTS_TV" SMALLINT DEFAULT NULL, 
		"EVENT_DEFAULT_LOCATION_ID" BIGINT DEFAULT NULL, 
		"EVENT_DEFAULT_LOCATION_DETAIL" VARCHAR(1000 OCTETS) NOT NULL DEFAULT '', 
		"EVENT_DEFAULT_START_TIME" TIME DEFAULT NULL, 
		"EVENT_DEFAULT_END_TIME" TIME DEFAULT NULL, 
		"RT_REQUIRED" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_RTREQUIRED" CHECK ( RT_REQUIRED in(0,1) ),
		"RT_REQ_EVERY_TU" INTEGER DEFAULT NULL, 
		"RT_REQ_EVERY_TV" SMALLINT DEFAULT NULL, 
		"ADDED_TMS" TIMESTAMP(3) NOT NULL DEFAULT CURRENT TIMESTAMP, 
		"ADDED_BY" VARCHAR(12 OCTETS) NOT NULL DEFAULT 'SYSTEM', 
		"ARCHIVED_TMS" TIMESTAMP(3) DEFAULT NULL, 
		"ARCHIVED_BY" VARCHAR(12 OCTETS) DEFAULT NULL, 
		"ARCHIVED_REASONS" VARCHAR(500 OCTETS) NOT NULL DEFAULT '', 
		"UNARCHIVED_TMS" TIMESTAMP(3) DEFAULT NULL, 
		"UNARCHIVED_BY" VARCHAR(12 OCTETS) DEFAULT NULL, 
		"UNARCHIVED_REASONS" VARCHAR(500 OCTETS) NOT NULL DEFAULT '', 
		"DRAFT_OWNER" VARCHAR(12 OCTETS) DEFAULT NULL, 
		"EQUIPCLOTHING_REQS" VARCHAR(500 OCTETS) NOT NULL DEFAULT '', 
		"LUNCH_PROVIDED" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_LUNCHPROVIDED" CHECK ( LUNCH_PROVIDED in(0,1) ),
		"COURSE_NOTES" VARCHAR(1000 OCTETS) NOT NULL DEFAULT '', 
		"IS_MANDATORY" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_ISMANDATORY" CHECK ( IS_MANDATORY in (0,1) ),
		"SELF_BOOKABLE" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_SELFBOOKABLE" CHECK ( SELF_BOOKABLE in(0,1) ),
		"SELF_BOOK_TV" SMALLINT DEFAULT NULL, 
		"SELF_BOOK_TU" INTEGER DEFAULT NULL, 
		"SELF_CANCELLABLE" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_SELFCANCELLABLE" CHECK ( SELF_CANCELLABLE in(0,1) ),
		"SELF_CANC_TV" SMALLINT DEFAULT NULL, 
		"SELF_CANC_TU" INTEGER DEFAULT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;
CREATE TABLE "FGC_TRAINING_DEV"."COURSE_TEMPLATE_ADMINISTRATORS" (
		"TEMPLATE_ID" BIGINT NOT NULL, 
		"ADMINISTRATOR_ID" BIGINT NOT NULL, 
		"SEQ_NUM" SMALLINT NOT NULL DEFAULT 0,
		CONSTRAINT "CON_UNIQUEROWS" UNIQUE("TEMPLATE_ID", "ADMINISTRATOR_ID")
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;
CREATE TABLE "FGC_TRAINING_DEV"."COURSE_TEMPLATE_BOOK_APPROVAL_PARTIES" (
		"TEMPLATE_ID" BIGINT NOT NULL, 
		"PARTY_ID" BIGINT NOT NULL,
		CONSTRAINT "CON_UNIQUEROWS" UNIQUE("TEMPLATE_ID", "PARTY_ID")
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;
CREATE TABLE "FGC_TRAINING_DEV"."COURSE_TEMPLATE_CANC_APPROVAL_PARTIES" (
		"TEMPLATE_ID" BIGINT NOT NULL, 
		"PARTY_ID" BIGINT NOT NULL,
		CONSTRAINT "CON_UNIQUEROWS" UNIQUE("TEMPLATE_ID", "PARTY_ID")
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;
CREATE TABLE "FGC_TRAINING_DEV"."EVENT_TEMPLATES" (
		"T_ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 0 INCREMENT BY 1 MINVALUE 0 NO CYCLE NO CACHE NO ORDER ), 
		CONSTRAINT "PK" PRIMARY KEY("T_ID"),
		"CATALOGUE_ID" INTEGER NOT NULL, 
		"COURSE_TEMPLATE_ID" BIGINT DEFAULT NULL, 
		"SEQ_NUM" SMALLINT DEFAULT NULL, 
		"VENDOR_ID" BIGINT DEFAULT NULL, 
		"EVENT_NAME" VARCHAR(200 OCTETS) NOT NULL, 
		"EVENT_DESC" VARCHAR(1000 OCTETS) NOT NULL DEFAULT '', 
		"PHASE_NUM" SMALLINT DEFAULT NULL, 
		CONSTRAINT "CON_PHASENUM" CHECK ( PHASE_NUM in( null, 1, 2, 3 ) ),
		"ILEARN_FLAG" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_ILEARNFLAG" CHECK ( ILEARN_FLAG in(0,1) ),
		"MIN_NUM_ATTENDEES" SMALLINT DEFAULT NULL, 
		"MAX_NUM_ATTENDEES" SMALLINT DEFAULT NULL, 
		"LOCATION_ID" BIGINT DEFAULT NULL, 
		"TIME_UNIT_ID" INTEGER DEFAULT NULL, 
		"TIME_VALUE" SMALLINT DEFAULT NULL, 
		"START_TIME" TIME DEFAULT NULL, 
		"END_TIME" TIME DEFAULT NULL, 
		"ATTENDEE_REQS" VARCHAR(1000 OCTETS) NOT NULL DEFAULT '', 
		"INTRA_LOCATION_DETAIL" VARCHAR(1000 OCTETS) NOT NULL DEFAULT '', 
		"ARCHIVED_REASONS" VARCHAR(500 OCTETS) NOT NULL DEFAULT '', 
		"TRAINER_REQS" VARCHAR(1000 OCTETS) NOT NULL DEFAULT '', 
		"ADDED_TMS" TIMESTAMP(3) NOT NULL DEFAULT CURRENT TIMESTAMP, 
		"ADDED_BY" VARCHAR(12 OCTETS) NOT NULL DEFAULT 'SYSTEM', 
		"ARCHIVED_TMS" TIMESTAMP(3) DEFAULT NULL, 
		"ARCHIVED_BY" VARCHAR(12 OCTETS) DEFAULT NULL, 
		"DRAFT_OWNER" VARCHAR(12 OCTETS) DEFAULT NULL, 
		"EQUIPCLOTHING_REQS" VARCHAR(500 OCTETS) NOT NULL DEFAULT '', 
		"LUNCH_PROVIDED" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_LUNCHPROVIDED" CHECK ( LUNCH_PROVIDED in(0,1) ),
		"IS_MANDATORY" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_ISMANDATORY" CHECK ( IS_MANDATORY in (0,1) ),
		"OBJECTIVES_OUTCOMES" VARCHAR(1000 OCTETS) NOT NULL DEFAULT '', 
		"SELF_BOOKABLE" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_SELFBOOKABLE" CHECK ( SELF_BOOKABLE in(0,1) ),
		"SELF_BOOK_TV" SMALLINT DEFAULT NULL, 
		"SELF_BOOK_TU" INTEGER DEFAULT NULL, 
		"SELF_CANCELLABLE" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_SELFCANCELLABLE" CHECK ( SELF_CANCELLABLE in(0,1) ),
		"SELF_CANC_TV" SMALLINT DEFAULT NULL, 
		"SELF_CANC_TU" INTEGER DEFAULT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;
CREATE TABLE "FGC_TRAINING_DEV"."EVENT_TEMPLATE_ADMINISTRATORS" (
		"TEMPLATE_ID" BIGINT NOT NULL, 
		"ADMINISTRATOR_ID" BIGINT NOT NULL, 
		"SEQ_NUM" SMALLINT NOT NULL DEFAULT 0,
		CONSTRAINT "CON_UNIQUEROWS" UNIQUE("TEMPLATE_ID", "ADMINISTRATOR_ID")
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;
CREATE TABLE "FGC_TRAINING_DEV"."EVENT_TEMPLATE_SKILLSQUALS" (
		"TEMPLATE_ID" BIGINT NOT NULL, 
		"SQ_ID" BIGINT NOT NULL,
		CONSTRAINT "CON_UNIQUEROWS" UNIQUE("TEMPLATE_ID", "SQ_ID")
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;

	
--########################################################################################
--# START: REFERENCE DATA for Course, Event, Relational Data
--########################################################################################
	
	
	
	
CREATE TABLE "FGC_TRAINING_DEV"."REF_ATTENDANCE_STATUSES" (
		"S_ID" SMALLINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 0 INCREMENT BY 1 MINVALUE 0 NO CYCLE NO CACHE NO ORDER ), 
		CONSTRAINT "PK" PRIMARY KEY("S_ID"),
		"S_NAME" VARCHAR(40 OCTETS) NOT NULL, 
		"ADDED_TMS" TIMESTAMP(3) NOT NULL DEFAULT CURRENT TIMESTAMP, 
		"ADDED_BY" VARCHAR(12 OCTETS) NOT NULL DEFAULT 'SYSTEM', 
		"SEQ_NUM" SMALLINT NOT NULL DEFAULT 0
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;
CREATE TABLE "FGC_TRAINING_DEV"."REF_BOOKING_APPROVAL_PARTIES" (
		"P_ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 0 INCREMENT BY 1 MINVALUE 0 NO CYCLE NO CACHE NO ORDER ), 
		CONSTRAINT "PK" PRIMARY KEY("P_ID"),
		"P_NAME" VARCHAR(40 OCTETS) NOT NULL, 
		"SEQ_NUM" BIGINT NOT NULL DEFAULT 0, 
		"ADDED_TMS" TIMESTAMP(3) NOT NULL DEFAULT CURRENT TIMESTAMP, 
		"ADDED_BY" VARCHAR(12 OCTETS) NOT NULL DEFAULT 'SYSTEM', 
		"ARCHIVED_TMS" TIMESTAMP(3) DEFAULT NULL, 
		"ARCHIVED_BY" VARCHAR(12 OCTETS) DEFAULT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;
CREATE TABLE "FGC_TRAINING_DEV"."REF_BOOKING_STATUSES" (
		"S_ID" SMALLINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 0 INCREMENT BY 1 MINVALUE 0 NO CYCLE NO CACHE NO ORDER ), 
		CONSTRAINT "PK" PRIMARY KEY("S_ID"),
		"S_NAME" VARCHAR(40 OCTETS) NOT NULL, 
		"ADDED_TMS" TIMESTAMP(3) NOT NULL DEFAULT CURRENT TIMESTAMP, 
		"ADDED_BY" VARCHAR(12 OCTETS) NOT NULL DEFAULT 'SYSTEM', 
		"SEQ_NUM" SMALLINT NOT NULL DEFAULT 0
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;
CREATE TABLE "FGC_TRAINING_DEV"."REF_CANCELLATION_APPROVAL_PARTIES" (
		"P_ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 0 INCREMENT BY 1 MINVALUE 0 NO CYCLE NO CACHE NO ORDER ), 
		CONSTRAINT "PK" PRIMARY KEY("P_ID"),
		"P_NAME" VARCHAR(40 OCTETS) NOT NULL, 
		"SEQ_NUM" BIGINT NOT NULL DEFAULT 0, 
		"ADDED_TMS" TIMESTAMP(3) NOT NULL DEFAULT CURRENT TIMESTAMP, 
		"ADDED_BY" VARCHAR(12 OCTETS) NOT NULL DEFAULT 'SYSTEM', 
		"ARCHIVED_TMS" TIMESTAMP(3) DEFAULT NULL, 
		"ARCHIVED_BY" VARCHAR(12 OCTETS) DEFAULT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;
CREATE TABLE "FGC_TRAINING_DEV"."REF_DISTRICTS" (
		"D_ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 0 INCREMENT BY 1 MINVALUE 0 NO CYCLE NO CACHE NO ORDER ), 
		CONSTRAINT "PK" PRIMARY KEY("D_ID"),
		"D_NAME" VARCHAR(30 OCTETS) NOT NULL, 
		"ADDED_TMS" TIMESTAMP(3) NOT NULL DEFAULT CURRENT TIMESTAMP, 
		"ADDED_BY" VARCHAR(12 OCTETS) NOT NULL DEFAULT 'SYSTEM', 
		"ARCHIVED_TMS" TIMESTAMP(3) DEFAULT NULL, 
		"ARCHIVED_BY" VARCHAR(12 OCTETS) DEFAULT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;
CREATE TABLE "FGC_TRAINING_DEV"."REF_PEOPLE" (
		"P_EMP_ID" VARCHAR(12 OCTETS) NOT NULL, 
		"P_USERNAME" VARCHAR(320 OCTETS) NOT NULL, 
		CONSTRAINT "CON_PUNAME" UNIQUE ("P_USERNAME"),
		CONSTRAINT "PK" PRIMARY KEY("P_EMP_ID", "P_USERNAME"),
		"P_UUID" VARCHAR(40 OCTETS) NOT NULL DEFAULT '', 
		"ADDED_TMS" TIMESTAMP(3) NOT NULL DEFAULT CURRENT TIMESTAMP, 
		"ADDED_BY" VARCHAR(12 OCTETS) NOT NULL DEFAULT 'SYSTEM', 
		"IS_CURRENT" DECIMAL(1,0) NOT NULL DEFAULT 1, --new records are always the latest.
		CONSTRAINT "CON_ISCURRENT" CHECK( IS_CURRENT in(0,1) ),
		"NAME_SHORT" VARCHAR(30 OCTETS) NOT NULL DEFAULT '', 
		"NAME_LONG" VARCHAR(100 OCTETS) NOT NULL DEFAULT '', 
		"MAIN_ROLE_NAME" VARCHAR(100 OCTETS) NOT NULL DEFAULT '', 
		"MAIN_ROLE_LOC" VARCHAR(40 OCTETS) NOT NULL DEFAULT '', 
		"MAIN_ROLE_MGR_EMPID" VARCHAR(12 OCTETS) DEFAULT NULL, 
		"MAIN_ROLE_MGR_UUID" VARCHAR(40 OCTETS) NOT NULL DEFAULT '', 
		"EMAIL_ADDRESS" VARCHAR(320 OCTETS) NOT NULL DEFAULT '', 
		"UPDATED_TMS" TIMESTAMP(3) DEFAULT NULL, 
		"UPDATED_BY" VARCHAR(12 OCTETS) DEFAULT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;
CREATE TABLE "FGC_TRAINING_DEV"."REF_SKILLS_QUALS_ETC" (
		"SQ_ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 0 INCREMENT BY 1 MINVALUE 0 NO CYCLE NO CACHE NO ORDER ), 
		CONSTRAINT "PK" PRIMARY KEY("SQ_ID"),
		"SQ_VENDOR_ID" BIGINT DEFAULT NULL, 
		"SQ_NAME" VARCHAR(100 OCTETS) NOT NULL, 
		"SQ_NAME_SHORT" VARCHAR(24 OCTETS) DEFAULT NULL, 
		"SQ_TYPE_ID" BIGINT NOT NULL, 
		"SQ_LEVEL" SMALLINT DEFAULT NULL, 
		"SQ_IS_CORE" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_SQISCORE" CHECK ( SQ_IS_CORE IN (0,1) ),
		"SQ_IS_COMMANDER" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_SQISCOMMANDER" CHECK ( SQ_IS_COMMANDER in(0,1) ),
		"SQ_EXPIRES" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_SQEXPIRES" CHECK ( SQ_EXPIRES IN (0,1) ),
		"SQ_EXPIRY_UNIT_ID" INTEGER DEFAULT NULL, 
		"SQ_EXPIRY_VALUE" SMALLINT DEFAULT NULL, 
		"ADDED_TMS" TIMESTAMP(3) NOT NULL DEFAULT CURRENT TIMESTAMP, 
		"ADDED_BY" VARCHAR(12 OCTETS) NOT NULL DEFAULT 'SYSTEM', 
		"ARCHIVED_TMS" TIMESTAMP(3) DEFAULT NULL, 
		"ARCHIVED_BY" VARCHAR(12 OCTETS) DEFAULT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;
CREATE TABLE "FGC_TRAINING_DEV"."REF_SQ_TYPES" (
		"T_ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 0 INCREMENT BY 1 MINVALUE 0 NO CYCLE NO CACHE NO ORDER ), 
		CONSTRAINT "PK" PRIMARY KEY("T_ID"),
		"T_CODE" VARCHAR(24 OCTETS) NOT NULL, 
		"T_NAME" VARCHAR(48 OCTETS) NOT NULL, 
		"T_DESC" VARCHAR(200 OCTETS) NOT NULL DEFAULT '', 
		"ADDED_TMS" TIMESTAMP(3) NOT NULL DEFAULT CURRENT TIMESTAMP, 
		"ADDED_BY" VARCHAR(12 OCTETS) NOT NULL DEFAULT 'SYSTEM', 
		"ARCHIVED_TMS" TIMESTAMP(3) DEFAULT NULL, 
		"ARCHIVED_BY" VARCHAR(12 OCTETS) DEFAULT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;
CREATE TABLE "FGC_TRAINING_DEV"."REF_SQ_TYPE_GRADES" (
		"G_ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 0 INCREMENT BY 1 MINVALUE 0 NO CYCLE NO CACHE NO ORDER ), 
		CONSTRAINT "PK" PRIMARY KEY("G_ID"),
		"SQ_TYPE_ID" BIGINT NOT NULL, 
		"G_NAME" VARCHAR(100 OCTETS) NOT NULL, 
		"ADDED_TMS" TIMESTAMP(3) NOT NULL DEFAULT CURRENT TIMESTAMP, 
		"ADDED_BY" VARCHAR(12 OCTETS) NOT NULL DEFAULT 'SYSTEM', 
		"ARCHIVED_TMS" TIMESTAMP(3) DEFAULT NULL, 
		"ARCHIVED_BY" VARCHAR(12 OCTETS) DEFAULT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;
CREATE TABLE "FGC_TRAINING_DEV"."REF_TIME_UNITS" (
		"U_ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 0 INCREMENT BY 1 MINVALUE 0 NO CYCLE NO CACHE NO ORDER ), 
		CONSTRAINT "PK" PRIMARY KEY("U_ID"),
		"U_NAME" VARCHAR(12 OCTETS) NOT NULL, 
		"ADDED_TMS" TIMESTAMP(3) NOT NULL DEFAULT CURRENT TIMESTAMP, 
		"ADDED_BY" VARCHAR(12 OCTETS) NOT NULL DEFAULT 'SYSTEM', 
		"ARCHIVED_TMS" TIMESTAMP(3) DEFAULT NULL, 
		"ARCHIVED_BY" VARCHAR(12 OCTETS) DEFAULT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;
CREATE TABLE "FGC_TRAINING_DEV"."REF_TRAINERS" (
		"T_ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 0 INCREMENT BY 1 MINVALUE 0 NO CYCLE NO CACHE NO ORDER ), 
		CONSTRAINT "PK" PRIMARY KEY("T_ID"),
		"T_VENDOR_ID" BIGINT NOT NULL, 
		"EMPLOYEE_ID" VARCHAR(12 OCTETS) DEFAULT NULL, 
		"T_NAME" VARCHAR(100 OCTETS) NOT NULL, 
		"T_TEAM_NAME" VARCHAR(100 OCTETS) NOT NULL, 
		"ADDED_TMS" TIMESTAMP(3) NOT NULL DEFAULT CURRENT TIMESTAMP, 
		"ADDED_BY" VARCHAR(12 OCTETS) NOT NULL DEFAULT 'SYSTEM', 
		"ARCHIVED_TMS" TIMESTAMP(3) DEFAULT NULL, 
		"ARCHIVED_BY" VARCHAR(12 OCTETS) DEFAULT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;
CREATE TABLE "FGC_TRAINING_DEV"."REF_TR_ADMINISTRATORS" (
		"A_ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 0 INCREMENT BY 1 MINVALUE 0 NO CYCLE NO CACHE NO ORDER ), 
		CONSTRAINT "PK" PRIMARY KEY("A_ID"),
		"A_VENDOR_ID" BIGINT NOT NULL, 
		"EMPLOYEE_ID" VARCHAR(12 OCTETS) DEFAULT NULL, 
		"A_NAME" VARCHAR(100 OCTETS) NOT NULL, 
		"A_TEAM_NAME" VARCHAR(100 OCTETS) NOT NULL, 
		"ADDED_TMS" TIMESTAMP(3) NOT NULL DEFAULT CURRENT TIMESTAMP, 
		"ADDED_BY" VARCHAR(12 OCTETS) NOT NULL DEFAULT 'SYSTEM', 
		"ARCHIVED_TMS" TIMESTAMP(3) DEFAULT NULL, 
		"ARCHIVED_BY" VARCHAR(12 OCTETS) DEFAULT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;
CREATE TABLE "FGC_TRAINING_DEV"."REF_TR_LOCATIONS" (
		"L_ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 0 INCREMENT BY 1 MINVALUE 0 NO CYCLE NO CACHE NO ORDER ), 
		CONSTRAINT "PK" PRIMARY KEY("L_ID"),
		"DISTRICT_ID" BIGINT DEFAULT NULL, 
		"L_NAME" VARCHAR(100 OCTETS) NOT NULL, 
		"L_DESC" VARCHAR(200 OCTETS) DEFAULT NULL, 
		"L_ADDRESS" VARCHAR(200 OCTETS) NOT NULL, 
		"L_CONTACT" VARCHAR(100 OCTETS) DEFAULT NULL, 
		"L_NOTES" VARCHAR(250 OCTETS) DEFAULT NULL, 
		"L_CAPACITY" INTEGER DEFAULT NULL, 
		"ADDED_TMS" TIMESTAMP(3) NOT NULL DEFAULT CURRENT TIMESTAMP, 
		"ADDED_BY" VARCHAR(12 OCTETS) NOT NULL DEFAULT 'SYSTEM', 
		"ARCHIVED_TMS" TIMESTAMP(3) DEFAULT NULL, 
		"ARCHIVED_BY" VARCHAR(12 OCTETS) DEFAULT NULL, 
		"ARRIVAL_INSTR" VARCHAR(250 OCTETS) DEFAULT NULL, 
		"CAR_PARKING" VARCHAR(250 OCTETS) DEFAULT NULL, 
		"IS_OURS" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_ISOURS" CHECK ( IS_OURS in(0,1) )
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;
CREATE TABLE "FGC_TRAINING_DEV"."REF_TR_VENDORS" (
		"V_ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 0 INCREMENT BY 1 MINVALUE 0 NO CYCLE NO CACHE NO ORDER ), 
		CONSTRAINT "PK" PRIMARY KEY("V_ID"),
		"V_NAME" VARCHAR(100 OCTETS) NOT NULL, 
		"V_DESC" VARCHAR(200 OCTETS) DEFAULT NULL, 
		"V_ADDRESS" VARCHAR(200 OCTETS) NOT NULL, 
		"V_CONTACT" VARCHAR(100 OCTETS) DEFAULT NULL, 
		"V_NOTES" VARCHAR(250 OCTETS) DEFAULT NULL, 
		"ADDED_TMS" TIMESTAMP(3) NOT NULL DEFAULT CURRENT TIMESTAMP, 
		"ADDED_BY" VARCHAR(12 OCTETS) NOT NULL DEFAULT 'SYSTEM', 
		"ARCHIVED_TMS" TIMESTAMP(3) DEFAULT NULL, 
		"ARCHIVED_BY" VARCHAR(12 OCTETS) DEFAULT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;

--########################################################################################
--# START: VERSION HISTORY for Course Instances, Event Instances, Relational Data and Bookings (NOT attendance)
--########################################################################################
CREATE TABLE "FGC_TRAINING_DEV"."VERHIST_COURSE_INSTANCES" ( --removed the created_tms and created_by colums (compared to the published instances table)
    "CHANGE_ID" CHAR(36) NOT NULL,
		CONSTRAINT "PK" PRIMARY KEY("CHANGE_ID"),
		"I_ID" BIGINT NOT NULL, 
		CONSTRAINT "CON_UNIQUEROWS" UNIQUE("CHANGE_ID", "I_ID"),
		"CATALOGUE_ID" INTEGER NOT NULL, 
		"COURSE_TEMPLATE_ID" BIGINT DEFAULT NULL, 
		"VENDOR_ID" BIGINT NOT NULL, 
		"COURSE_NAME" VARCHAR(200 OCTETS) NOT NULL, 
		"COURSE_DESC" VARCHAR(1000 OCTETS) NOT NULL DEFAULT '', 
		"PHASE_NUM" SMALLINT DEFAULT NULL, 
		CONSTRAINT "CON_PHASENUM" CHECK ( PHASE_NUM in( null, 1, 2, 3 ) ),
		"ILEARN_FLAG" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_ILEARNFLAG" CHECK ( ILEARN_FLAG in(0,1) ),
		"MIN_NUM_ATTENDEES" SMALLINT DEFAULT NULL, 
		"MAX_NUM_ATTENDEES" SMALLINT DEFAULT NULL, 
		"ATTENDEE_REQS" VARCHAR(1000 OCTETS) NOT NULL DEFAULT '', 
		"TRAINER_REQS" VARCHAR(1000 OCTETS) NOT NULL DEFAULT '', 
		"COURSE_START_DATETIME" TIMESTAMP(3) NOT NULL, 
		"COURSE_LEN_TU" INTEGER DEFAULT NULL, 
		"COURSE_LEN_TV" SMALLINT DEFAULT NULL, 
		"NUM_EVENTS" SMALLINT NOT NULL DEFAULT 0, 
		"RT_REQUIRED" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_RTREQUIRED" CHECK ( RT_REQUIRED in(0,1) ),
		"RT_REQ_EVERY_TU" INTEGER DEFAULT NULL, 
		"RT_REQ_EVERY_TV" SMALLINT DEFAULT NULL, 
		"MODIFIED_TMS" TIMESTAMP(3) DEFAULT NULL, 
		"MODIFIED_BY" VARCHAR(12 OCTETS) DEFAULT NULL, 
		"MODIFIED_REASONS" VARCHAR(500 OCTETS) NOT NULL DEFAULT '', 
		"CANCELLED_TMS" TIMESTAMP(3) DEFAULT NULL, 
		"CANCELLED_BY" VARCHAR(12 OCTETS) DEFAULT NULL, 
		"CANCELLED_REASONS" VARCHAR(500 OCTETS) NOT NULL DEFAULT '', 
		"COURSE_END_DATETIME" TIMESTAMP(3) NOT NULL, 
		"EQUIPCLOTHING_REQS" VARCHAR(500 OCTETS) NOT NULL DEFAULT '', 
		"LUNCH_PROVIDED" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_LUNCHPROVIDED" CHECK ( LUNCH_PROVIDED in(0,1) ),
		"COURSE_NOTES" VARCHAR(1000 OCTETS) NOT NULL DEFAULT '', 
		"IS_MANDATORY" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		"SELF_BOOKABLE" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_SELFBOOKABLE" CHECK ( SELF_BOOKABLE in(0,1) ),
		"SELF_BOOK_TV" SMALLINT DEFAULT NULL, 
		"SELF_BOOK_TU" INTEGER DEFAULT NULL, 
		CONSTRAINT "CON_ISMANDATORY" CHECK ( IS_MANDATORY in (0,1) ),
		"SELF_CANCELLABLE" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_SELFCANCELLABLE" CHECK ( SELF_CANCELLABLE in(0,1) ),
		"SELF_CANC_TV" SMALLINT DEFAULT NULL, 
		"SELF_CANC_TU" INTEGER DEFAULT NULL,
		--The "created" columns are not required by the VerHist functionality but some shared SQL Helper routines expected them to be present:-
		"CREATED_TMS" TIMESTAMP(3) NULL DEFAULT NULL,
		"CREATED_BY"  VARCHAR(12)  NULL DEFAULT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;
CREATE TABLE "FGC_TRAINING_DEV"."VERHIST_COURSE_INST_BOOK_APPROVAL_PARTIES" (
		"CHANGE_ID"   CHAR(36) NOT NULL,
		"INSTANCE_ID" BIGINT NOT NULL, 
		"PARTY_ID"    BIGINT NOT NULL,
    CONSTRAINT "CON_UNIQUEROWS" UNIQUE("CHANGE_ID", "INSTANCE_ID", "PARTY_ID")
)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;
CREATE TABLE "FGC_TRAINING_DEV"."VERHIST_COURSE_INST_CANC_APPROVAL_PARTIES" (
		"CHANGE_ID"   CHAR(36) NOT NULL,
		"INSTANCE_ID" BIGINT NOT NULL, 
		"PARTY_ID"    BIGINT NOT NULL,
    CONSTRAINT "CON_UNIQUEROWS" UNIQUE("CHANGE_ID", "INSTANCE_ID", "PARTY_ID")
)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;
CREATE TABLE "FGC_TRAINING_DEV"."VERHIST_EVENT_INSTANCES" ( --removed the created_tms and created_by colums (compared to the published instances table)
		"CHANGE_ID" CHAR(36) NOT NULL,
		"I_ID" BIGINT NOT NULL,
		CONSTRAINT "CON_UNIQUEROWS" UNIQUE("CHANGE_ID", "I_ID"),
		"COURSE_INSTANCE_ID" BIGINT DEFAULT NULL, 
		"EVENT_TEMPLATE_ID" BIGINT DEFAULT NULL, 
		"CATALOGUE_ID" INTEGER NOT NULL, 
		"VENDOR_ID" BIGINT DEFAULT NULL, 
		"EVENT_NAME_PREFIX" VARCHAR(40 OCTETS) DEFAULT NULL, 
		"EVENT_NAME_SHORT" VARCHAR(24 OCTETS) NOT NULL DEFAULT '', 
		"EVENT_NAME" VARCHAR(200 OCTETS) NOT NULL, 
		"EVENT_DESC" VARCHAR(1000 OCTETS) NOT NULL DEFAULT '', 
		"PHASE_NUM" SMALLINT DEFAULT NULL, 
		CONSTRAINT "CON_PHASENUM" CHECK ( PHASE_NUM       in( null, 1, 2, 3 ) ),
		"ILEARN_FLAG" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_ILEARNFLAG" CHECK ( ILEARN_FLAG     in(0,1) ),
		"MIN_NUM_ATTENDEES" SMALLINT DEFAULT NULL, 
		"MAX_NUM_ATTENDEES" SMALLINT DEFAULT NULL, 
		"START_DATETIME" TIMESTAMP(3) NOT NULL, 
		"END_DATETIME" TIMESTAMP(3) NOT NULL, 
		"TIME_UNIT_ID" INTEGER DEFAULT NULL, 
		"TIME_VALUE" SMALLINT DEFAULT NULL, 
		"LOCATION_ID" BIGINT DEFAULT NULL, 
		"INTRA_LOCATION_DETAIL" VARCHAR(1000 OCTETS) NOT NULL DEFAULT '', 
		"ATTENDEE_REQS" VARCHAR(1000 OCTETS) NOT NULL DEFAULT '', 
		"TRAINER_REQS" VARCHAR(1000 OCTETS) NOT NULL DEFAULT '', 
		"MODIFIED_TMS" TIMESTAMP(3) DEFAULT NULL, 
		"MODIFIED_BY" VARCHAR(12 OCTETS) DEFAULT NULL, 
		"MODIFIED_REASONS" VARCHAR(500 OCTETS) NOT NULL DEFAULT '', 
		"CANCELLED_TMS" TIMESTAMP(3) DEFAULT NULL, 
		"CANCELLED_BY" VARCHAR(12 OCTETS) DEFAULT NULL, 
		"CANCELLED_REASONS" VARCHAR(500 OCTETS) NOT NULL DEFAULT '', 
		"EQUIPCLOTHING_REQS" VARCHAR(500 OCTETS) NOT NULL DEFAULT '', 
		"LUNCH_PROVIDED" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_LUNCHPROVIDED" CHECK ( LUNCH_PROVIDED in(0,1) ),
		"OBJECTIVES_OUTCOMES" VARCHAR(1000 OCTETS) NOT NULL DEFAULT '', 
		"ATTENDANCE_PUBLISHED_TMS" TIMESTAMP(3) DEFAULT NULL, 
		"ATTENDANCE_PUBLISHED_BY" VARCHAR(12 OCTETS) DEFAULT NULL, 
		"IS_MANDATORY" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_ISMANDATORY" CHECK ( IS_MANDATORY     in(0,1) ),
		"SELF_BOOKABLE" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_SELFBOOKABLE" CHECK ( SELF_BOOKABLE   in(0,1) ),
		"SELF_BOOK_TV" SMALLINT DEFAULT NULL, 
		"SELF_BOOK_TU" INTEGER DEFAULT NULL, 
		"SELF_CANCELLABLE" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		CONSTRAINT "CON_SELFCANCELLABLE" CHECK ( SELF_CANCELLABLE in(0,1) ),
		"SELF_CANC_TV" SMALLINT DEFAULT NULL, 
		"SELF_CANC_TU" INTEGER DEFAULT NULL,
		--The "created" columns are not required by the VerHist functionality but some shared SQL Helper routines expected them to be present:-
		"CREATED_TMS" TIMESTAMP(3) NULL DEFAULT NULL,
		"CREATED_BY"  VARCHAR(12)  NULL DEFAULT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;
CREATE TABLE "FGC_TRAINING_DEV"."VERHIST_EVENT_INST_ATTENDANCE" (
		"CHANGE_ID" CHAR(36) NOT NULL,
		"EVENT_INSTANCE_ID" BIGINT NOT NULL, 
		"ATTENDEE_ID" VARCHAR(12 OCTETS) NOT NULL, 

    CONSTRAINT "CON_UNIQUEROWS" UNIQUE("CHANGE_ID", "EVENT_INSTANCE_ID", "ATTENDEE_ID"),
		
		"ATTENDEE_ADDED_ON" TIMESTAMP(3) NOT NULL, 
		"ATTENDEE_ADDED_BY" VARCHAR(12 OCTETS), 

		"BOOKING_STATUS_ID" SMALLINT NOT NULL DEFAULT 1, 
		"BOOKING_UPDATED_ON" TIMESTAMP(3) DEFAULT NULL, 
		"BOOKING_UPDATED_BY" VARCHAR(12 OCTETS) DEFAULT NULL,
		"ATT_STATUS_ID" SMALLINT DEFAULT NULL, 		
		"ATTENDANCE_UPDATE_ON" TIMESTAMP(3), 
		"ATTENDANCE_UPDATE_BY" VARCHAR(12 OCTETS), 

		"REASON_FOR_NONATTENDANCE" VARCHAR(5000 OCTETS), 
		"INJURY_OCCURRED" DECIMAL(1 , 0) NOT NULL DEFAULT 0, 
		"INJURY_OCCURRED_DETAILS" VARCHAR(5000 OCTETS), 
		"ADDITIONAL_NOTES" VARCHAR(5000 OCTETS) 
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;
	
	
--########################################################################################
--# START: Feedback Process Related Tables
--########################################################################################
CREATE TABLE "FGC_TRAINING_DEV"."REF_FEEDBACK_QUESTIONS" (
		"F_QUESTION_CODE" VARCHAR(10 OCTETS) NOT NULL, 	
		"F_QUESTION" VARCHAR(1000 OCTETS) NOT NULL, 	
		"F_QUESTION_SEQ" INTEGER NOT NULL, 
		"ADDED_TMS" TIMESTAMP(3) NOT NULL DEFAULT CURRENT TIMESTAMP, 
		"ADDED_BY" VARCHAR(12 OCTETS) NOT NULL DEFAULT 'SYSTEM', 
		"ARCHIVED_TMS" TIMESTAMP(3) DEFAULT NULL, 
		"ARCHIVED_BY" VARCHAR(12 OCTETS) DEFAULT NULL, 
		CONSTRAINT "PK" PRIMARY KEY
		("F_QUESTION_CODE")
)
ORGANIZE BY ROW
DATA CAPTURE NONE 
COMPRESS NO;


CREATE TABLE "FGC_TRAINING_DEV"."COURSE_INST_FEEDBACK" (
		"CF_ID" 				BIGINT 					NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 0 INCREMENT BY 1 MINVALUE 0 NO CYCLE NO CACHE NO ORDER ),
		"COURSE_INSTANCE_ID" 	BIGINT 					NOT NULL,
		"ATTENDEE_ID" 			VARCHAR(12 OCTETS) 		NOT NULL, 
		"ADDITIONAL_COMMENTS"   VARCHAR(5000 OCTETS) 	DEFAULT NULL, 
		"FEEDBACK_PROVIDED_ON"	TIMESTAMP(3) 			DEFAULT NULL, 
		"FEEDBACK_PROVIDED_BY"	VARCHAR(12 OCTETS) 		DEFAULT NULL, 
		CONSTRAINT "PK" PRIMARY KEY
		("CF_ID")
)
ORGANIZE BY ROW
DATA CAPTURE NONE 
COMPRESS NO;


CREATE TABLE "FGC_TRAINING_DEV"."COURSE_INST_FEEDBACK_REVIEW" (
		"CFR_ID" 				  BIGINT 					NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 0 INCREMENT BY 1 MINVALUE 0 NO CYCLE NO CACHE NO ORDER ),
		"CF_ID" 				  BIGINT 					NOT NULL,
		"FEEDBACK_REVIEW_NOTES"   VARCHAR(5000 OCTETS) 	DEFAULT NULL, 
		"FEEDBACK_REVIEWED_ON"	  TIMESTAMP(3) 			DEFAULT NULL, 
		"FEEDBACK_REVIEWED_BY"	  VARCHAR(12 OCTETS) 		DEFAULT NULL, 
		CONSTRAINT "PK" PRIMARY KEY
		("CFR_ID")
)
ORGANIZE BY ROW
DATA CAPTURE NONE 
COMPRESS NO;


CREATE TABLE "FGC_TRAINING_DEV"."COURSE_INST_FEEDBACK_COMMENTS" (
		"FC_ID" 				BIGINT 					NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 0 INCREMENT BY 1 MINVALUE 0 NO CYCLE NO CACHE NO ORDER ),
		"CF_ID" 				BIGINT 					NOT NULL,
		"FEEDBACK_COMMENTS"		VARCHAR(5000 OCTETS) 	DEFAULT NULL,
		"COMMENT_TYPE"			VARCHAR(50 OCTETS) 		NOT NULL,
		CONSTRAINT "PK" PRIMARY KEY
		("FC_ID")
)
ORGANIZE BY ROW
DATA CAPTURE NONE 
COMPRESS NO;


CREATE TABLE "FGC_TRAINING_DEV"."COURSE_INST_FEEDBACK_RATING" (
		"FR_ID" 					BIGINT 					NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 0 INCREMENT BY 1 MINVALUE 0 NO CYCLE NO CACHE NO ORDER ),
		"CF_ID" 					BIGINT 					NOT NULL,
		"FEEDBACK_QUESTION_CODE" 	VARCHAR(10 OCTETS) 		NOT NULL, 
		"FEEDBACK_RATING"			INTEGER			   		NULL,
		"FEEDBACK_REASON"			VARCHAR(5000 OCTETS) 	NULL, 
		CONSTRAINT "PK" PRIMARY KEY
		("FR_ID")
)
ORGANIZE BY ROW
DATA CAPTURE NONE 
COMPRESS NO;

	
--########################################################################################
--# START: SCHEMA PERMISSIONS AND COMMENT
--########################################################################################
GRANT ALTERIN  ON SCHEMA "FGC_TRAINING_DEV" TO USER "FGC_TRAINING_DEV" WITH GRANT OPTION;
GRANT CREATEIN ON SCHEMA "FGC_TRAINING_DEV" TO USER "FGC_TRAINING_DEV" WITH GRANT OPTION;
GRANT DROPIN   ON SCHEMA "FGC_TRAINING_DEV" TO USER "FGC_TRAINING_DEV" WITH GRANT OPTION;

COMMENT ON SCHEMA "FGC_TRAINING_DEV" IS
'Schema to house artefacts related to the storage and management of Training data including: Courses; Events/Activities; Vendors; Trainers/Admins; Trainees; Skills/Qualifications etc.';

--END.